# Disabling default bar

bar {
    swaybar_command swaybar
	font IosevkaNerdFontMono 10
	# tray_output none
	status_command while true; do echo "Bat: $(cat /sys/class/power_supply/BAT0/capacity)%"; sleep 5; done
}
